// <auto-generated />
namespace ApiFP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AlterFacturaQtyDescargaCC : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AlterFacturaQtyDescargaCC));
        
        string IMigrationMetadata.Id
        {
            get { return "201902141811476_AlterFacturaQtyDescargaCC"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
