// <auto-generated />
namespace ApiFP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class AddEstadoFactura : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddEstadoFactura));
        
        string IMigrationMetadata.Id
        {
            get { return "201902111555393_AddEstadoFactura"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
